### PR TITLE
Update af.js

### PR DESCRIPTION
**Pull request by MoskitoHorst**
Add tint remote messages, remove condition frameType===1, maybe wrong, but in my case it works, please review. The remote transmits frameType===0

### CODE REVIEW

**Comment by Koenkk** [comment]
Is this only for the scenes button? I'm really unsure about the side effects caused by this.

**Comment by MoskitoHorst** [comment]
You told me About the first lines. We Need them for the normal keys.
The Change in the if-statement is only for the Scenes button.
When I tried to receive the Messages by foundation entries, the program starved. Am I correct: the foundation messages are used like relays for data?

**Comment by MoskitoHorst** [comment]
I reviewed the upstream and upstream-upstream of this project. I now implemented the same way, they did for statusChangeNotification, this should be without side effects.

**Comment by Koenkk** [comment]
Which upstream repo do you mean?

**Comment by MoskitoHorst** [comment]
you forked from kirovilya/zigbee-shepherd, it  has this Extension (emit on lines 666 - 669), this is forked from zigbeer/zigbee-shepherd  and there on lines 659-660 you see, it is not present.

For me it seems, everyone, who needs the function to do events on some message, will put it in here.

**Comment by Koenkk** [comment]
@MoskitoHorst I'm not seeing this on: https://github.com/kirovilya/zigbee-shepherd/blob/master/lib/components/af.js#L666 , am I looking at the wrong place?

**Comment by MoskitoHorst** [comment]
if you compare this to https://github.com/zigbeer/zigbee-shepherd/blob/master/lib/components/af.js#659 you see an emit on 'report' only. kirivilya added an emit for 'statusChangeNotification'  later. This seems to me a list of generated emit's, as someone need them.

**Comment by Koenkk** [comment]
I understand now, thanks!

**Comment by MoskitoHorst** [comment]
I also have to thank you, nice to work with you

**Pull request merged**
