### PR TITLE
Add extra version attributes to devices #1213

### PR DESCRIPTION
**Pull request by tb-killa**
WIP for #1213

### CODE REVIEW

**Comment by tb-killa** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/1213

**Comment by Koenkk** [comment]
This one can be merged, right?

**Comment by tb-killa** [comment]
I include this informations on zigbee shepherd but we need the parse on Z2M too. 
And we should check if we need this type or informations in this big back really or maybe short them up. 

Let's merge them and do rework after we found the needing informations.

**Comment by Koenkk** [comment]
ok, thanks!

**Pull request merged**
